import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Plus, Trash2, Copy, Calendar, BarChart3, List, Save, AlertTriangle } from 'lucide-react';
import './styles.css';

const STORAGE_KEY = 'mheScheduler.v2';
const PHASES = ['Kickoff','Engineering','Procurement','Site Readiness','Install','Controls','Testing','Closeout'];
const STATUS = ['Not Started','In Progress','Complete','On Hold'];
const RESOURCES = ['PM','Application Engineer','Project Engineer','Controls Engineer','Safety Lead','Site Superintendent','Millwright Crew','Electrical Crew','Controls Tech','Software/WMS Resource','Vendor Tech','Commissioning Team'];
const SUPPLIERS = ['Internal','Hy-Tek Controls','Matthews Automation','Conveyor Vendor','Sorter Vendor','Rack Vendor','Electrical Contractor','Installation Contractor','Controls Contractor','WMS/WES Vendor','OEM Vendor'];
const TASK_LIBRARY = [
  ['Project Kickoff Meeting','Kickoff',1,'Project Management'],['Site Survey / Field Verify','Kickoff',2,'Project Management'],['Customer Data / SKU / Order Profile Review','Kickoff',3,'Project Management'],['Permit / Code / AHJ Review','Kickoff',5,'Project Management'],
  ['System Layout Approval','Engineering',5,'Engineering'],['Conveyor Detail Engineering','Engineering',10,'Engineering'],['Sorter Detail Engineering','Engineering',10,'Engineering'],['Pick Module / Mezzanine Engineering','Engineering',15,'Engineering'],['Rack / Shelving Engineering','Engineering',8,'Engineering'],['Robotics / ASRS Interface Design','Engineering',12,'Engineering'],['Controls Architecture / IO Map','Engineering',8,'Controls'],['Network / IT / WMS Interface Design','Engineering',8,'Controls'],['Safety Risk Assessment','Engineering',5,'Safety'],
  ['Order MDR Conveyor','Procurement',3,'Conveyor'],['Order Belt Conveyor / Inclines','Procurement',3,'Conveyor'],['Order Spiral / VRC / Lift','Procurement',3,'Conveyor'],['Order Sorter / Diverts / Merge Equipment','Procurement',4,'Sortation'],['Order Print-and-Apply / Scanners / Scales','Procurement',3,'Automation'],['Order Autobagger / Pack Automation','Procurement',4,'Packing'],['Order Rack / Shelving / Carton Flow','Procurement',5,'Storage'],['Order Pick Module / Mezzanine Steel','Procurement',5,'Structures'],['Order Robotics / AMR / ASRS Equipment','Procurement',5,'Robotics'],['Order Panels / Drives / PLC Hardware','Procurement',4,'Controls'],['Order Devices / Photoeyes / Encoders / VFDs','Procurement',4,'Controls'],['Order Guarding / E-Stops / Safety Devices','Procurement',3,'Safety'],
  ['Material Delivery / Receiving at Site','Site Readiness',5,'Site'],['Floor Prep / Concrete Repair','Site Readiness',4,'Site'],['Anchor Layout / Survey Lines','Site Readiness',2,'Site'],['Electrical Service / Power Drops Ready','Site Readiness',5,'Electrical'],['Network Drops / IDF / Wi-Fi Ready','Site Readiness',4,'IT'],
  ['Install Pallet Rack / Shelving','Install',7,'Storage'],['Install Pick Module / Mezzanine','Install',15,'Structures'],['Install MDR Conveyor','Install',10,'Conveyor'],['Install Belt Conveyor / Inclines','Install',7,'Conveyor'],['Install Curves / Transfers / Spurs','Install',6,'Conveyor'],['Install Spiral / VRC / Lift','Install',7,'Conveyor'],['Install Sorter / Diverts / Merge','Install',10,'Sortation'],['Install Scanners / Scales / Print-and-Apply','Install',4,'Automation'],['Install Autobagger / Pack Stations','Install',5,'Packing'],['Install Robotics / AMR / ASRS Field Equipment','Install',10,'Robotics'],['Install Guarding / Fencing / Bollards','Install',5,'Safety'],
  ['Panel Build / FAT','Controls',10,'Controls'],['Controls Wiring / Termination','Controls',8,'Controls'],['PLC / HMI Programming','Controls',10,'Controls'],['WES / WCS / WMS Integration','Controls',10,'Controls'],['Scanner / Scale / P&A Configuration','Controls',4,'Controls'],['Safety Circuit Validation','Controls',3,'Safety'],
  ['Mechanical Checkout','Testing',3,'Commissioning'],['Electrical IO Checkout','Testing',4,'Commissioning'],['Controls Functional Test','Testing',4,'Commissioning'],['Dry Cycle / Product Test','Testing',4,'Commissioning'],['Throughput / Rate Test','Testing',3,'Commissioning'],['Operator Training','Testing',2,'Training'],
  ['Punch List / Corrections','Closeout',5,'Closeout'],['As-Builts / O&M Manuals','Closeout',5,'Closeout'],['Final Acceptance / Sign-Off','Closeout',1,'Closeout']
].map(([name, phase, defaultDuration, category]) => ({ name, phase, defaultDuration, category }));

const toDate = s => { const [y,m,d] = String(s).split('-').map(Number); return new Date(y, m - 1, d); };
const fmt = d => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const addDays = (s,n) => { const d = toDate(s); d.setDate(d.getDate() + Number(n)); return fmt(d); };
const daysBetween = (a,b) => Math.round((toDate(b)-toDate(a))/86400000);
const duration = (a,b) => Math.max(1, daysBetween(a,b)+1);
const pretty = s => s ? `${String(toDate(s).getMonth()+1).padStart(2,'0')}/${String(toDate(s).getDate()).padStart(2,'0')}/${toDate(s).getFullYear()}` : '';
const csvEscape = value => `"${String(value ?? '').replaceAll('"','""')}"`;
const safeName = name => (name || 'schedule').replace(/[^a-z0-9-_ ]/gi, '').trim().replace(/\s+/g,'_');
const resourcesOf = r => String(r.resourcesText || '').split(',').map(x => x.trim()).filter(Boolean);
function downloadFile(filename, content, type) { const blob = new Blob([content], { type }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = filename; document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(url); }
function normalizeRows(rows) { return rows.map(r => ({ baselineStart:'', baselineFinish:'', actualStart:'', actualFinish:'', ...r, preds:(r.preds||[]).map(p => ({ predUid:p.predUid || p.uid || p.taskUid || '', type:p.type || 'FS', lag:Number(p.lag)||0 })).filter(p => p.predUid) })); }
function wouldCreateCycle(rows, taskUid, predUid) { const next = rows.map(r => r.uid === taskUid ? { ...r, preds:[...r.preds,{predUid,type:'FS',lag:0}] } : r); return findCycles(next).length > 0; }
function findCycles(rows) { const byUid = new Map(rows.map(r => [r.uid, r])); const visiting = new Set(); const visited = new Set(); const cycles = [];
  function dfs(uid, path) { if (visiting.has(uid)) { const i = path.indexOf(uid); cycles.push(path.slice(i).concat(uid)); return; } if (visited.has(uid)) return; visiting.add(uid); const row = byUid.get(uid); (row?.preds || []).forEach(p => dfs(p.predUid, [...path, uid])); visiting.delete(uid); visited.add(uid); }
  rows.forEach(r => dfs(r.uid, [])); return cycles;
}
function autoSchedule(rows) { if (findCycles(rows).length) return rows; let out = normalizeRows(rows); const maxPasses = Math.max(25, out.length * 2);
  for (let pass = 0; pass < maxPasses; pass++) { let changed = false; const byUid = new Map(out.map(t => [t.uid, t]));
    out = out.map(task => { if (!task.preds.length) return task; let start = task.start; let finish = task.finish; const dur = Number(task.duration) || 1;
      for (const p of task.preds) { const pred = byUid.get(p.predUid); if (!pred) continue; const lag = Number(p.lag || 0);
        if (p.type === 'FS') start = [start, addDays(pred.finish, lag + 1)].sort().at(-1);
        if (p.type === 'SS') start = [start, addDays(pred.start, lag)].sort().at(-1);
        if (p.type === 'FF') finish = [finish, addDays(pred.finish, lag)].sort().at(-1);
        if (p.type === 'SF') finish = [finish, addDays(pred.start, lag)].sort().at(-1);
      }
      if (finish && (!start || toDate(addDays(finish, -(dur-1))) > toDate(start))) start = addDays(finish, -(dur-1));
      finish = addDays(start, dur - 1); if (start !== task.start || finish !== task.finish) changed = true; return { ...task, start, finish };
    }); if (!changed) break;
  } return out;
}
function computeCritical(rows) { if (!rows.length || findCycles(rows).length) return new Set(); const byUid = new Map(rows.map(r => [r.uid, r])); const successors = new Map(rows.map(r => [r.uid, []])); rows.forEach(r => r.preds.forEach(p => successors.get(p.predUid)?.push({ succUid:r.uid, type:p.type, lag:p.lag })));
  const projectEnd = rows.map(r => r.finish).sort().at(-1); const late = new Map(rows.map(r => [r.uid, { lf: projectEnd, ls: addDays(projectEnd, -(r.duration-1)) }]));
  for (let pass = 0; pass < rows.length + 3; pass++) { let changed = false; for (const r of [...rows].reverse()) { let lf = late.get(r.uid).lf; let ls = late.get(r.uid).ls;
      for (const edge of successors.get(r.uid) || []) { const succ = byUid.get(edge.succUid); const succLate = late.get(edge.succUid); if (!succ || !succLate) continue; const lag = Number(edge.lag || 0); let candLf = lf; let candLs = ls;
        if (edge.type === 'FS') candLf = addDays(succLate.ls, -(lag + 1));
        if (edge.type === 'SS') candLs = addDays(succLate.ls, -lag);
        if (edge.type === 'FF') candLf = addDays(succLate.lf, -lag);
        if (edge.type === 'SF') candLs = addDays(succLate.lf, -lag);
        if (toDate(candLf) < toDate(lf)) lf = candLf; if (toDate(candLs) < toDate(ls)) ls = candLs;
      }
      const derivedLs = addDays(lf, -(r.duration-1)); if (toDate(derivedLs) < toDate(ls)) ls = derivedLs; const derivedLf = addDays(ls, r.duration-1); if (toDate(derivedLf) < toDate(lf)) lf = derivedLf;
      if (lf !== late.get(r.uid).lf || ls !== late.get(r.uid).ls) { late.set(r.uid,{lf,ls}); changed = true; }
    } if (!changed) break;
  }
  return new Set(rows.filter(r => daysBetween(r.start, late.get(r.uid).ls) === 0).map(r => r.uid));
}
function resourceConflicts(rows) { const conflicts = []; const byRes = new Map(); rows.forEach(r => resourcesOf(r).forEach(res => { if (!byRes.has(res)) byRes.set(res, []); byRes.get(res).push(r); })); byRes.forEach((list,res) => { for (let i=0;i<list.length;i++) for (let j=i+1;j<list.length;j++) { const a=list[i], b=list[j]; if (toDate(a.start) <= toDate(b.finish) && toDate(b.start) <= toDate(a.finish)) conflicts.push({ resource:res, a, b }); } }); return conflicts; }
function exportCsv(projectName, rows, critical) { const headers = ['ID','Task Name','Phase','Predecessors','Start','Duration','Finish','Baseline Start','Baseline Finish','Actual Start','Actual Finish','Variance Days','Critical','Zone','Resources','Supplier','Status','Category'];
  const lines = rows.map(r => [r.id,r.name,r.phase,r.preds.map(p => rows.find(x=>x.uid===p.predUid)?.id + p.type + (p.lag?`+${p.lag}`:'')).join(','),r.start,r.duration,r.finish,r.baselineStart,r.baselineFinish,r.actualStart,r.actualFinish,r.baselineFinish?daysBetween(r.baselineFinish,r.finish):'',critical.has(r.uid)?'Yes':'No',r.zone,r.resourcesText,r.supplier,r.status,r.category].map(csvEscape).join(',')); downloadFile(`${safeName(projectName)}.csv`, [headers.join(','), ...lines].join('\n'), 'text/csv;charset=utf-8'); }
function exportProjectXml(projectName, rows) { const esc = s => String(s ?? '').replace(/[<>&'"]/g, c => ({'<':'&lt;','>':'&gt;','&':'&amp;',"'":'&apos;','"':'&quot;'}[c])); const taskUidToXmlUid = new Map(rows.map((r,i)=>[r.uid,i+1]));
  const tasks = rows.map((r,i) => `<Task><UID>${i+1}</UID><ID>${i+1}</ID><Name>${esc(r.name)}</Name><Start>${r.start}T08:00:00</Start><Finish>${r.finish}T17:00:00</Finish><Duration>PT${r.duration*8}H0M0S</Duration><Text1>${esc(r.phase)}</Text1><Text2>${esc(r.zone)}</Text2><Text3>${esc(r.supplier)}</Text3>${r.preds.map(p=>`<PredecessorLink><PredecessorUID>${taskUidToXmlUid.get(p.predUid)}</PredecessorUID><Type>${{FS:1,SS:2,FF:3,SF:4}[p.type] || 1}</Type><LinkLag>${p.lag*4800}</LinkLag></PredecessorLink>`).join('')}</Task>`).join(''); downloadFile(`${safeName(projectName)}.xml`, `<?xml version="1.0" encoding="UTF-8"?><Project xmlns="http://schemas.microsoft.com/project"><Name>${esc(projectName)}</Name><Tasks>${tasks}</Tasks></Project>`, 'application/xml;charset=utf-8'); }
function exportHtml(projectName, rows, critical) { const html = `<!doctype html><html><head><meta charset="utf-8"><title>${projectName}</title><style>body{font-family:Arial;margin:24px}table{border-collapse:collapse;width:100%;font-size:12px}td,th{border:1px solid #ddd;padding:6px}th{background:#f2f2f2;text-align:left}.c{background:#fee2e2}</style></head><body><h1>${projectName}</h1><p>Use browser print to save as PDF.</p><table><thead><tr><th>ID</th><th>Task</th><th>Phase</th><th>Start</th><th>Finish</th><th>Dur</th><th>Critical</th><th>Preds</th><th>Zone</th><th>Resources</th><th>Supplier</th></tr></thead><tbody>${rows.map(r=>`<tr class="${critical.has(r.uid)?'c':''}"><td>${r.id}</td><td>${r.name}</td><td>${r.phase}</td><td>${r.start}</td><td>${r.finish}</td><td>${r.duration}</td><td>${critical.has(r.uid)?'Yes':'No'}</td><td>${r.preds.map(p=>(rows.find(x=>x.uid===p.predUid)?.id||'?')+p.type+(p.lag?`+${p.lag}`:'')).join(', ')}</td><td>${r.zone}</td><td>${r.resourcesText}</td><td>${r.supplier}</td></tr>`).join('')}</tbody></table></body></html>`; downloadFile(`${safeName(projectName)}_printable.html`, html, 'text/html;charset=utf-8'); }

function App(){
  const loaded = useRef(false); const [projectName,setProjectName] = useState('MHE Project Schedule'); const [rows,setRows] = useState([]); const [view,setView] = useState('list'); const [filter,setFilter] = useState('All'); const [search,setSearch] = useState(''); const [dupMode,setDupMode] = useState('clear'); const nextId = useRef(100); const nextUid = useRef(1);
  useEffect(() => { try { const raw = localStorage.getItem(STORAGE_KEY); if (raw) { const data = JSON.parse(raw); setProjectName(data.projectName || 'MHE Project Schedule'); const clean = normalizeRows(data.rows || []); setRows(autoSchedule(clean)); nextId.current = Math.max(100, ...clean.map(r=>Number(r.id)||0)); nextUid.current = Math.max(1, ...clean.map(r=>Number(String(r.uid).replace('u',''))||0)) + 1; } } catch(e) { console.warn('LocalStorage load failed', e); } finally { loaded.current = true; } }, []);
  useEffect(() => { if (!loaded.current) return; localStorage.setItem(STORAGE_KEY, JSON.stringify({ projectName, rows })); }, [projectName, rows]);
  const counts = useMemo(()=>rows.reduce((m,r)=>m.set(r.name,(m.get(r.name)||0)+1),new Map()),[rows]); const library = TASK_LIBRARY.filter(t => (filter==='All'||t.phase===filter) && t.name.toLowerCase().includes(search.toLowerCase()));
  const cycles = useMemo(()=>findCycles(rows), [rows]); const critical = useMemo(()=>computeCritical(rows), [rows]); const conflicts = useMemo(()=>resourceConflicts(rows), [rows]);
  const addTask = t => { const today = fmt(new Date()); const entry=(counts.get(t.name)||0)+1; const task={uid:`u${nextUid.current++}`,id:String(++nextId.current),name:t.name,phase:t.phase,start:today,duration:t.defaultDuration,finish:addDays(today,t.defaultDuration-1),zone:`Zone ${entry}`,resourcesText:'',preds:[],supplier:'',status:'Not Started',entry,category:t.category,baselineStart:'',baselineFinish:'',actualStart:'',actualFinish:''}; setRows(r=>autoSchedule([...r,task])); };
  const patch = (uid, change) => setRows(r => autoSchedule(r.map(x => { if(x.uid!==uid) return x; let n={...x,...change}; if(change.start || change.duration) n.finish=addDays(n.start, (Number(n.duration)||1)-1); if(change.finish && !change.start && !change.duration) n.duration=duration(n.start,n.finish); return n; })));
  const duplicate = uid => setRows(r => { const t=r.find(x=>x.uid===uid); if(!t) return r; const entry=(counts.get(t.name)||0)+1; const copy={...t,uid:`u${nextUid.current++}`,id:String(++nextId.current),entry,zone:`Zone ${entry}`,preds:dupMode==='copy'?[...t.preds]:[],baselineStart:'',baselineFinish:'',actualStart:'',actualFinish:''}; return autoSchedule([...r, copy]); });
  const remove = uid => setRows(r => autoSchedule(r.filter(x=>x.uid!==uid).map(x=>({...x,preds:x.preds.filter(p=>p.predUid!==uid)}))));
  const addPred = (uid, predUid, type, lag) => setRows(r => { if (!predUid) return r; if (uid === predUid) { alert('A task cannot depend on itself.'); return r; } if (wouldCreateCycle(r, uid, predUid)) { alert('Circular dependency blocked.'); return r; } return autoSchedule(r.map(x => x.uid===uid && !x.preds.some(p=>p.predUid===predUid) ? {...x, preds:[...x.preds,{predUid,type,lag:Number(lag)||0}]} : x)); });
  const removePred = (uid,predUid) => setRows(r => autoSchedule(r.map(x => x.uid===uid ? {...x,preds:x.preds.filter(p=>p.predUid!==predUid)} : x)));
  const setBaseline = () => setRows(r => r.map(x => ({ ...x, baselineStart:x.start, baselineFinish:x.finish })));
  const clearSaved = () => { localStorage.removeItem(STORAGE_KEY); alert('Saved browser copy cleared. Current screen is unchanged until you edit or refresh.'); };
  const exportNow = kind => { if(!rows.length) return alert('Schedule empty'); if(kind==='CSV') exportCsv(projectName,rows,critical); if(kind==='MS Project XML') exportProjectXml(projectName,rows); if(kind==='Printable PDF HTML') exportHtml(projectName,rows,critical); if(kind==='JSON') downloadFile(`${safeName(projectName)}.json`, JSON.stringify({projectName, rows}, null, 2), 'application/json;charset=utf-8'); };
  return <div className="app"><header><div className="brand">MH</div><input className="project" value={projectName} onChange={e=>setProjectName(e.target.value)} /><button onClick={()=>setView('list')} className={view==='list'?'active':''}><List size={16}/> List</button><button onClick={()=>setView('gantt')} className={view==='gantt'?'active':''}><BarChart3 size={16}/> Gantt</button><button title="Set baseline dates to current scheduled dates" onClick={setBaseline}><Save size={16}/> Baseline</button><select title="Duplicate behavior" value={dupMode} onChange={e=>setDupMode(e.target.value)}><option value="clear">Duplicate clears preds</option><option value="copy">Duplicate copies preds</option></select><select onChange={e=>exportNow(e.target.value)} defaultValue=""><option value="" disabled>Export...</option><option>CSV</option><option>MS Project XML</option><option>Printable PDF HTML</option><option>JSON</option></select><button onClick={clearSaved}>Clear Saved</button></header><main><aside><input placeholder="Search task library" value={search} onChange={e=>setSearch(e.target.value)} /><div className="chips"><button className={filter==='All'?'active':''} onClick={()=>setFilter('All')}>All</button>{PHASES.map(p=><button key={p} className={filter===p?'active':''} onClick={()=>setFilter(p)}>{p.slice(0,4)}</button>)}</div>{PHASES.filter(p=>filter==='All'||p===filter).map(p=><section key={p}><h3>{p}</h3>{library.filter(t=>t.phase===p).map(t=><button key={t.name} className="tasklib" onClick={()=>addTask(t)}><Plus size={14}/><span>{t.name}<small>{t.defaultDuration}d • {t.category}</small></span>{counts.get(t.name)>0 && <b>{counts.get(t.name)}x</b>}</button>)}</section>)}</aside><section className="workspace"><div className="hint"><Calendar size={16}/> LocalStorage auto-save is on. Predecessors now use hidden stable UIDs, so changing displayed task IDs does not break logic. Critical path is highlighted red.</div>{cycles.length>0 && <div className="error"><AlertTriangle size={16}/> Circular dependency found: {cycles[0].map(uid=>rows.find(r=>r.uid===uid)?.id || uid).join(' -> ')}</div>}{conflicts.length>0 && <div className="warn"><AlertTriangle size={16}/> Resource overlap: {conflicts.slice(0,3).map(c=>`${c.resource} on ${c.a.id}/${c.b.id}`).join('; ')}{conflicts.length>3 ? ` + ${conflicts.length-3} more` : ''}</div>}{view==='list'?<TaskTable rows={rows} patch={patch} duplicate={duplicate} remove={remove} addPred={addPred} removePred={removePred} critical={critical}/>:<Gantt rows={rows} critical={critical}/>}<footer>{rows.length} tasks {rows.length>0 && `• ${pretty(rows.map(r=>r.start).sort()[0])} to ${pretty(rows.map(r=>r.finish).sort().at(-1))}`} • Critical: {critical.size} • Resource conflicts: {conflicts.length}</footer></section></main></div>;
}
function TaskTable({rows,patch,duplicate,remove,addPred,removePred,critical}) { if(!rows.length) return <div className="blank">Blank slate. Add typical MHE equipment tasks from the library.</div>; return <div className="tablewrap"><table><thead><tr>{['ID','Task Name','Phase','Preds','Start','Dur','Finish','Baseline','Variance','Actual','Zone','Resources','Supplier','Status','Act'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.uid} className={critical.has(r.uid)?'critical':''}><td><input value={r.id} onChange={e=>patch(r.uid,{id:e.target.value})}/>{critical.has(r.uid)&&<small>Critical</small>}</td><td><input value={r.name} onChange={e=>patch(r.uid,{name:e.target.value})}/><small>E{r.entry} • {r.category}</small></td><td><select value={r.phase} onChange={e=>patch(r.uid,{phase:e.target.value})}>{PHASES.map(p=><option key={p}>{p}</option>)}</select></td><td><PredEditor row={r} rows={rows} addPred={addPred} removePred={removePred}/></td><td><input type="date" value={r.start} onChange={e=>patch(r.uid,{start:e.target.value})}/><small>{pretty(r.start)}</small></td><td><input type="number" min="1" value={r.duration} onChange={e=>patch(r.uid,{duration:Number(e.target.value)||1})}/></td><td><input type="date" value={r.finish} onChange={e=>patch(r.uid,{finish:e.target.value})}/><small>{pretty(r.finish)}</small></td><td><small>{r.baselineStart?`${pretty(r.baselineStart)} to ${pretty(r.baselineFinish)}`:'No baseline'}</small></td><td><b>{r.baselineFinish ? `${daysBetween(r.baselineFinish,r.finish)}d` : ''}</b></td><td><input type="date" value={r.actualStart} onChange={e=>patch(r.uid,{actualStart:e.target.value})}/><input type="date" value={r.actualFinish} onChange={e=>patch(r.uid,{actualFinish:e.target.value})}/></td><td><input value={r.zone} onChange={e=>patch(r.uid,{zone:e.target.value})}/></td><td><input list="resources" value={r.resourcesText} onChange={e=>patch(r.uid,{resourcesText:e.target.value})}/></td><td><input list="suppliers" value={r.supplier} onChange={e=>patch(r.uid,{supplier:e.target.value})}/></td><td><select value={r.status} onChange={e=>patch(r.uid,{status:e.target.value})}>{STATUS.map(s=><option key={s}>{s}</option>)}</select></td><td><button onClick={()=>duplicate(r.uid)}><Copy size={14}/></button><button onClick={()=>remove(r.uid)}><Trash2 size={14}/></button></td></tr>)}</tbody></table><datalist id="resources">{RESOURCES.map(x=><option key={x} value={x}/>)}</datalist><datalist id="suppliers">{SUPPLIERS.map(x=><option key={x} value={x}/>)}</datalist></div>; }
function PredEditor({row,rows,addPred,removePred}) { const [predUid,setPredUid] = useState(''); const [type,setType] = useState('FS'); const [lag,setLag] = useState(0); return <div className="preds"><div>{row.preds.map(p=>{ const pred = rows.find(x=>x.uid===p.predUid); return <span className="pill" key={p.predUid}>{pred?.id || '?'}{p.type}{p.lag?`+${p.lag}`:''}<button onClick={()=>removePred(row.uid,p.predUid)}>x</button></span>; })}</div><select value={predUid} onChange={e=>setPredUid(e.target.value)}><option value="">Pred</option>{rows.filter(x=>x.uid!==row.uid).map(x=><option key={x.uid} value={x.uid}>{x.id} {x.name.slice(0,18)}</option>)}</select><select value={type} onChange={e=>setType(e.target.value)}>{['FS','SS','FF','SF'].map(x=><option key={x}>{x}</option>)}</select><input type="number" value={lag} onChange={e=>setLag(e.target.value)}/><button onClick={()=>{ addPred(row.uid,predUid,type,lag); setPredUid(''); }}>+</button></div>; }
function Gantt({rows,critical}) { if(!rows.length) return <div className="blank">Add tasks to see Gantt.</div>; const min=toDate(rows.map(r=>r.start).sort()[0]); const max=toDate(rows.map(r=>r.finish).sort().at(-1)); const days=Math.round((max-min)/86400000)+8; const px=26; const left=s=>Math.round((toDate(s)-min)/86400000)*px; return <div className="gantt" style={{minWidth:days*px+290}}>{rows.map(r=><div className="ganttrow" key={r.uid}><div className="ganttname"><b>{r.id}</b> {r.name}</div><div className="ganttline"><div className={critical.has(r.uid)?'bar cbar':'bar'} style={{left:left(r.start),width:duration(r.start,r.finish)*px}}>{r.zone} • {r.duration}d</div></div></div>)}</div>; }
createRoot(document.getElementById('root')).render(<App />);
